# ============== DEPLOYMENT VARIABLES ============================
INTERNAL_TLS_ENABLED: false
SNI_PROPAGATION_ENABLED: false
MONITORING_ENABLED: true
CLOUD_TOPOLOGY_KEY: kubernetes.io/hostname
READONLY_CONTAINER_FILE_SYSTEM_ENABLED: false

DB_CREDENTIALS_SECRET: "control-plane-db-credentials"

# ============== SERVICE VARIABLES ============================
LOG_LEVEL: "info"

TRACING_ENABLED: false
TRACING_HOST: 'nc-diagnostic-agent'
TRACING_SAMPLER_RATELIMITING: 10
TRACING_SAMPLER_PROBABILISTIC: 0.01

VAULT_INTEGRATION: false
GRPC_GO_RETRY: "on"
GOGC: "20"

GATEWAYS_ACCESS_CONTROL_MAX_AGE: -1
GATEWAYS_ALLOWED_HEADERS: "*"
GATEWAYS_ALLOWED_ORIGIN: "*.qubership.org:*, *.qubership.cloud:*"
GATEWAYS_COMPRESSION_ENABLED: "false"
TIMEOUT: 120000
GOOGLERE2_MAXSIZE: 200
GOOGLERE2_WARN_SIZE: 150
SWIM_PORT: 12345
CONNECTION_BUFFER_SIZE_MEGABYTES: 10
IP_STACK: "v4"
PUBLIC_GATEWAY_ROUTE_HOST: ''
PRIVATE_GATEWAY_ROUTE_HOST: ''
EXECUTION_MODE: active
DISABLE_IP_ROUTE_REGISTRATION: true
DNS_LOOKUP_FAMILY: 'V6_PREFERRED'
ORIGIN_NAMESPACE: ""
PEER_NAMESPACE: ""
K8S_SERVICE_TYPE: 'CLUSTER_IP'
ECDH_CURVES: 'P-256,P-384'
CONSUL_ENABLED: false
CONSUL_URL: ''
